output "id" {
  description = "The ID of the Storage Account."
  value       = azurerm_storage_account.main.id
}

output "name" {
  description = "The Name of the Storage Account."
  value       = azurerm_storage_account.main.name
}

output "container_name" {
  description = "The name of the Storage Container."
  value       = azurerm_storage_container.main.name
}

output "blob_url" {
  description = "The URL of the uploaded application archive blob."
  value       = azurerm_storage_blob.app_archive.url
}

# Use the SAS token generated by data.azurerm_storage_account_blob_container_sas
# This SAS provides access relative to the storage account url + container name
output "container_sas_token" {
  description = "Shared Access Signature (SAS) token for the storage container (query string)."
  value       = data.azurerm_storage_account_blob_container_sas.app_blob_sas_for_acr.sas
  sensitive   = true
}